// ZK Oracle — Host Program (Prover)
// ==================================
// This program runs OUTSIDE the zkVM. It:
// 1. Reads oracle data (from CLI or stdin)
// 2. Feeds it into the guest program (the ZK circuit)
// 3. Runs the prover to generate a ZK proof
// 4. Outputs the proof + public journal (committed values)
//
// Think of this as the "launcher" that kicks off the ZK computation.

use anyhow::Result;
use clap::Parser;
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::fs;

// Import the guest program's ELF binary and image ID
// These are auto-generated by risc0-build from the methods crate
use methods::{ORACLE_GUEST_ELF, ORACLE_GUEST_ID};

/// ZK Oracle Prover — generates a ZK proof for oracle data
#[derive(Parser, Debug)]
#[command(author, version, about)]
struct Args {
    /// Path to the oracle data JSON file
    #[arg(short, long)]
    input: String,
}

fn main() -> Result<()> {
    // Parse CLI arguments
    let args = Args::parse();

    // Read the oracle data from the input file
    let oracle_data = fs::read_to_string(&args.input)?;
    println!("📊 Loaded oracle data from: {}", args.input);

    // Create the executor environment
    // The oracle data is passed as private input (not revealed in the proof)
    let env = ExecutorEnv::builder()
        .write(&oracle_data)?
        .build()?;

    println!("🔐 Generating ZK proof... (this may take a moment)");

    // Run the prover
    let prover = default_prover();
    let receipt = prover.prove(env, ORACLE_GUEST_ELF)?;

    // Verify the receipt locally (optional sanity check)
    receipt.receipt.verify(ORACLE_GUEST_ID)?;
    println!("✅ Proof verified locally!");

    // Extract the public journal (committed values from the guest)
    let journal_bytes = receipt.receipt.journal.bytes.clone();
    println!("📋 Journal (public output): {}", hex::encode(&journal_bytes));

    // Serialize the receipt (proof) for on-chain submission
    let proof_bytes = bincode::serialize(&receipt.receipt)?;
    println!("📦 Proof size: {} bytes", proof_bytes.len());

    // Save proof to file for the integration layer to pick up
    fs::write("output/proof.bin", &proof_bytes)?;
    fs::write("output/journal.bin", &journal_bytes)?;
    println!("💾 Proof and journal saved to output/");

    Ok(())
}
